script:
    - make

after_success:
    - bash ./deploy.sh

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-xetex
